spring:
  flyway:
    clean-disabled: true

  jpa:
    show-sql: false

  datasource:
    url: ${SPRING_DATABASE_URL}
    username: ${SPRING_DATABASE_USERNAME}
    password: ${SPRING_DATABASE_PASSWORD}

wutsi:
  platform:
    cache:
      type: memcached
      memcached:
        username: ${MEMCACHIER_USERNAME}
        password: ${MEMCACHIER_PASSWORD}
        servers: ${MEMCACHIER_SERVERS}
    stream:
      type: rabbitmq
      rabbitmq:
        url: ${CLOUDAMQP_URL}
  image-kit: # Configuration of integration with imagekit.io
    origin-url: "https://s3.amazonaws.com/prod-wutsi"
    endpoint-url: "https://ik.imagekit.io/toifevuwjn"

