ALTER TABLE T_ACCOUNT DROP COLUMN whatsapp;
ALTER TABLE T_ACCOUNT ADD COLUMN whatsapp VARCHAR(30);
ALTER TABLE T_ACCOUNT ADD COLUMN street VARCHAR(160);
ALTER TABLE T_ACCOUNT ADD COLUMN city_id BIGINT;
