ALTER TABLE T_ACCOUNT DROP COLUMN total_views;
ALTER TABLE T_ACCOUNT DROP COLUMN total_shares;
ALTER TABLE T_ACCOUNT DROP COLUMN total_chats;
ALTER TABLE T_ACCOUNT DROP COLUMN total_orders;
ALTER TABLE T_ACCOUNT DROP COLUMN total_sales;
ALTER TABLE T_ACCOUNT DROP COLUMN score;
ALTER TABLE T_ACCOUNT DROP COLUMN conversion;
